/**
 * Adversarial suite for the identity gate.
 *
 * The gate is the last thing standing between a render and a published
 * thumbnail of the wrong person. Everything here is a way of getting a `pass`
 * (or a merely-advisory `warn`) out of it without the face having been checked.
 * All of these worked against the gate as first written.
 */

import { describe, expect, it } from 'vitest';
import type { ReferenceAsset } from '@hexa/core';
import { identityGate } from '../src/gates/identity.js';
import type { GateSubject, VisionPort } from '../src/types.js';
import { ctx, embedding, flatBackground } from './helpers.js';

const FACE = { x: 0.28, y: 0.16, w: 0.18, h: 0.26 };
const GALLERY = [embedding(1), embedding(2)];
/** An unrelated person: cosine ≈ 0 against the gallery. */
const IMPOSTOR = embedding(99);

function port(vector: number[] | null, available = true): VisionPort {
  return { available: async () => available, embed: async () => (vector ? { vector } : null) };
}

function subject(over: Partial<GateSubject> = {}): GateSubject {
  return { playerId: 'peyz', handle: 'Peyz', faceRect: FACE, referenceEmbeddings: GALLERY, ...over };
}

function placeholderAsset(): ReferenceAsset {
  // Exactly what packages/assets' ensurePlaceholderAsset and the pipeline's
  // select stage register: owned, cleared, and not a photograph of anybody.
  return {
    id: 'placeholder:peyz',
    playerId: 'peyz',
    kind: 'portrait',
    path: 'placeholder://peyz.png',
    metrics: { width: 900, height: 1200, sharpness: 0, brightness: 0, contrast: 0, quality: 0 },
    provenance: {
      source: 'Hexa generated placeholder',
      license: 'owned',
      cleared: true,
      addedAt: new Date(0).toISOString(),
      notes: 'Schematic silhouette generated by Hexa.',
    },
    tags: ['placeholder', 'synthetic'],
  } as ReferenceAsset;
}

// ── 1. Threshold tampering ──────────────────────────────────────────────────

describe('attack: neutralising the gate through the threshold', () => {
  it('does not verify an impostor when the threshold is negative', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject()], vision: port(IMPOSTOR), request: { identityThreshold: -1 } }),
    );
    expect(
      findings.some((f) => f.severity === 'pass'),
      'a threshold of -1 turned a stranger into a verified player',
    ).toBe(false);
    expect(findings.some((f) => f.severity === 'fail' || f.severity === 'warn')).toBe(true);
  });

  it('does not verify an impostor when the threshold is zero', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject()], vision: port(IMPOSTOR), request: { identityThreshold: 0 } }),
    );
    expect(findings.some((f) => f.severity === 'pass')).toBe(false);
  });

  it('does not verify an impostor when the threshold is NaN', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject()], vision: port(IMPOSTOR), request: { identityThreshold: Number.NaN } }),
    );
    // `best < NaN` is false, so the original gate fell through to "verified".
    expect(findings.some((f) => f.severity === 'pass')).toBe(false);
    // …and no finding may report a comparison made against NaN.
    expect(findings.some((f) => /verified.*NaN|≥ NaN/.test(f.message))).toBe(false);
    expect(findings.some((f) => f.severity === 'fail')).toBe(true);
  });

  it('says out loud when a supplied threshold is unusable', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject()], vision: port(IMPOSTOR), request: { identityThreshold: 0 } }),
    );
    expect(findings.some((f) => /threshold/i.test(f.message))).toBe(true);
  });

  it('warns that a threshold below the impostor tail cannot separate people', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject()], vision: port(GALLERY[0]!), request: { identityThreshold: 0.02 } }),
    );
    expect(findings.some((f) => f.severity === 'warn' && /threshold/i.test(f.message))).toBe(true);
  });
});

// ── 2. Face rect tampering ──────────────────────────────────────────────────

describe('attack: pointing the gate at nothing', () => {
  it('fails, rather than warns, when the face rect is off-canvas', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, {
        subjects: [subject({ faceRect: { x: 9000, y: 9000, w: 200, h: 200 } })],
        vision: port(GALLERY[0]!),
      }),
    );
    expect(
      findings.some((f) => f.severity === 'fail'),
      'an off-canvas face rect produced no hard failure — the render would ship unverified',
    ).toBe(true);
  });

  it('fails when the face rect has zero area', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ faceRect: { x: 0.5, y: 0.5, w: 0, h: 0 } })], vision: port(GALLERY[0]!) }),
    );
    expect(findings.some((f) => f.severity === 'fail')).toBe(true);
  });

  it('fails when the face rect is negative-sized', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ faceRect: { x: 0.5, y: 0.5, w: -0.3, h: -0.3 } })], vision: port(GALLERY[0]!) }),
    );
    expect(findings.some((f) => f.severity === 'fail')).toBe(true);
  });

  it('still only warns about a genuinely small but present face', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ faceRect: { x: 0.5, y: 0.5, w: 0.006, h: 0.01 } })], vision: port(GALLERY[0]!) }),
    );
    expect(findings.some((f) => f.severity === 'fail')).toBe(false);
    expect(findings.some((f) => f.severity === 'warn')).toBe(true);
  });
});

// ── 3. Degenerate reference galleries ───────────────────────────────────────

describe('attack: reference galleries that cannot be compared', () => {
  it('never passes on a zero reference vector', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ referenceEmbeddings: [new Array(512).fill(0)] })], vision: port(IMPOSTOR) }),
    );
    expect(findings.some((f) => f.severity === 'pass')).toBe(false);
    // …and says the truth about why, rather than blaming a model mismatch.
    expect(findings.some((f) => /degenerate|zero|unusable/i.test(f.message))).toBe(true);
  });

  it('never passes on NaN inside a reference vector', async () => {
    const image = await flatBackground('#202030');
    const poisoned = [...GALLERY[0]!];
    poisoned[0] = Number.NaN;
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ referenceEmbeddings: [poisoned] })], vision: port(GALLERY[0]!) }),
    );
    expect(findings.some((f) => f.severity === 'pass')).toBe(false);
  });

  it('never passes on Infinity inside a reference vector', async () => {
    const image = await flatBackground('#202030');
    const poisoned = [...GALLERY[0]!];
    poisoned[3] = Number.POSITIVE_INFINITY;
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ referenceEmbeddings: [poisoned] })], vision: port(GALLERY[0]!) }),
    );
    expect(findings.some((f) => f.severity === 'pass')).toBe(false);
  });

  it('never passes when the probe itself is degenerate', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject()], vision: port(new Array(512).fill(0)) }),
    );
    expect(findings.some((f) => f.severity === 'pass')).toBe(false);
  });

  it('reports a dimension mismatch as a model mismatch, not a degenerate vector', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ referenceEmbeddings: [embedding(1, 512)] })], vision: port(embedding(1, 128)) }),
    );
    expect(findings[0]!.severity).toBe('warn');
    expect(findings[0]!.message).toMatch(/different models/);
  });
});

// ── 4. Opting out of verification ───────────────────────────────────────────

describe('attack: switching verification off', () => {
  it('never reports an anonymous subject as verified', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [{ playerId: 'x', handle: 'Silhouette', anonymous: true }] }),
    );
    const f = findings.find((x) => x.subjectId === 'x')!;
    expect(f.message).toMatch(/not verified|unverified/i);
    // A silent score of 1 lets "we did not check" average out as "excellent".
    expect(f.score ?? 1).toBeLessThan(1);
  });

  it('escalates an anonymous subject to a warning on a publish-grade request', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, {
        subjects: [{ playerId: 'x', handle: 'Silhouette', anonymous: true }],
        request: { requireClearedLicense: true },
      }),
    );
    expect(findings.find((f) => f.subjectId === 'x')!.severity).toBe('warn');
  });
});

// ── 5. Placeholders ─────────────────────────────────────────────────────────

describe('attack: shipping a placeholder as the player', () => {
  it('flags a placeholder subject instead of merely noting a missing gallery', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, { subjects: [subject({ referenceEmbeddings: [], assets: [placeholderAsset()] })] }),
    );
    expect(findings.some((f) => /placeholder|stand-in|synthetic/i.test(f.message))).toBe(true);
    expect(findings.some((f) => f.severity === 'pass')).toBe(false);
  });

  it('hard-fails a placeholder when the request demands publish-grade provenance', async () => {
    const image = await flatBackground('#202030');
    const findings = await identityGate.run(
      ctx(image, {
        subjects: [subject({ referenceEmbeddings: [], assets: [placeholderAsset()] })],
        request: { requireClearedLicense: true },
      }),
    );
    expect(
      findings.some((f) => f.severity === 'fail'),
      'a synthetic silhouette shipped as publish-grade likeness of a real player',
    ).toBe(true);
  });

  it('does not flag a real cleared photograph', async () => {
    const image = await flatBackground('#202030');
    const real = { ...placeholderAsset(), id: 'a1', path: 'peyz/01.jpg', tags: ['press-kit'] } as ReferenceAsset;
    const findings = await identityGate.run(
      ctx(image, {
        subjects: [subject({ assets: [real] })],
        vision: port(GALLERY[0]!),
        request: { requireClearedLicense: true },
      }),
    );
    expect(findings.some((f) => /placeholder/i.test(f.message))).toBe(false);
    expect(findings.some((f) => f.severity === 'pass')).toBe(true);
  });
});
